### ISSUE TITLE
message.sendTo (etc) don't return Promise

### ISSUE THREAD

**Issue by LoungeFlyZ** [abreits/amqp-ts#1]
It would be great if message.sendTo, queue.send etc... returned a Promise so callers can be assured the send completed correctly. 

Any plans to do something like this?

PS: thx for this lib... its a great help!

**Comment by abreits** [comment]
I would like to do that, but at the moment this is not possible.

amqp-ts uses amqplib underneath. The 'sendToQueue' method of amqplib does not have a callback or promise at all, so there is no way for me to know when the message has been sent.

So, no plans, unless amqplib adds a callback to it's send methods.

Thank you for letting me know you like the library!

**Comment by LoungeFlyZ** [comment]
Thanks abreits!  It looks like amqplib uses Buffer to write to the queue and that buf.write might be synchronous(?) so maybe this isn't needed anyway.

buf.write:
https://nodejs.org/api/buffer.html#buffer_buf_write_string_offset_length_encoding

We are a typescript shop so your lib is super useful.  Thanks again!
