### ISSUE TITLE
prefetch option present in source but not in built

### ISSUE THREAD

**Issue by enriched** [abreits/amqp-ts#13]
In the DeclarationOptions there is a [prefetch](https://github.com/abreits/amqp-ts/blob/master/src/amqp-ts.ts#L1033) but it is not present in [the DeclarationOptions in the compiled lib](https://github.com/abreits/amqp-ts/blob/master/lib/amqp-ts.d.ts#L99).

**Comment by abreits** [comment]
Thank you for the report, I have added it to the published declaration options.

**Comment by Sammons** [comment]
@abreits is this supposed to be in the 1.1.0 release?

**Comment by abreits** [comment]
It was added after the 1.1.0 release, I forgot to publish it. I have published it now (1.1.1 release)

**Comment by enriched** [comment]
Thank you!
