### ISSUE TITLE
nack(false) still requeues, nack needs allUpTo parameter

### ISSUE THREAD

**Issue by Sammons** [abreits/amqp-ts#14]
I ran into a delivery loop (event always failed, always redelivered), and found out that allUpTo is false when I pass false to nack, but requeue isn't being passed through.
http://www.squaremobius.net/amqp.node/channel_api.html#channel_nack

This is the suspect line, when I added false as the second parameter, the problem went away
https://github.com/abreits/amqp-ts/blob/master/src/amqp-ts.ts#L393

in the mean time we are using ack instead to deal with this.

**Comment by abreits** [comment]
Thank you for reporting this bug, I have fixed it (version 1.1.0). I have added the allUpTo parameter to the nack method, so it now correctly passes the parameters to the amqplib nack.

**Comment by Sammons** [comment]
Thank you!
