### ISSUE TITLE
getContent() always returns a string or json

### ISSUE THREAD

**Issue by marcelmaatkamp** [abreits/amqp-ts#3]
The function getContent() always returns a string which, in the case of binary data, causes data loss. Maybe the code should look in the contentType to determine if a string value has to be returned and raw data otherwise like this:
```
    Message.prototype.getContent = function () {
    console.log("getContent::Message "+this.properties.contentType+" received: " + this.content.length);

      var content = this.content;
      if(this.properties.contentType == "text/plain") {
        console.log("getContent::Message received plain text: " + content.length);
        content = this.content.toString();
      }
```
I have tested this with:
```
cat /usr/share/pixmaps/debian-logo.png | amqp-publish -u amqp://RABBITNODE -e images -C application/octet-stream
```
and the data is indeed of the correct size.

**Comment by abreits** [comment]
The Message.getContent() method is only provided for messages where you expect the content to be json or text (independent of the Message.properties.contentType). It is meant to be just a convenience method.

If you want more control over the message content you can access the Message.content and Message.properties directly (and perform the suggested checks yourself).
