### ISSUE TITLE
Promise not rejected on failed connection attempts.

### ISSUE THREAD

**Issue by maze-le** [abreits/amqp-ts#33]
When a connection attempt fails (_integration-test provided with incorrect credentials_), the Promises bound to:

```typescript
    connection.completeConfiguration()
    connection.initialized
```

are not rejected, instead, they are resolved and all errors are silently ignored. Reconnects continue to happen, even when reconnect-strategy is configured without retries: `{ retries: 0, interval: 1500 }`

**Comment by maze-le** [comment]
As a quick-and-dirty fix, I have just forked the repo and undone: [master (#29)]. 
 -- this fixes the issue, but also reintroduces the bug, fixed in: https://github.com/abreits/amqp-ts/pull/29

https://github.com/maze-le/amqp-ts/commit/34d03f8270ffeda829eeaa4e125da6bfd97f0264

**Comment by douglasrafael** [comment]
According to the documentation: `{retries: 0 // forever //, interval: 1500 // ms //}`. When you assign "retries = 0", it will be endless attempts.
Documentation [link >>](https://github.com/abreits/amqp-ts/wiki/Connection-class#constructor-).

**Comment by maze-le** [comment]
@douglasrafael: thanks! ...should have taken a closer look: it was an underlying issue managing the connection on my part. Strangely enough it didn't occur with v. 1.3.6
